apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tg-example
  template:
    metadata:
      labels:
        app: tg-example
    spec:
      containers:
      - image: farwydi/nasa-apod-bot:latest
        name: tg-example
        env:
          - name: NASA_API_KEY
            valueFrom:
              secretKeyRef:
                name: nasa-apod-bot
                key: api-key
          - name: ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: nasa-apod-bot
                key: endpoint
---
apiVersion: v1
kind: Service
metadata:
  name: tg-example
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "tg-example"
    port: 8080
  selector:
    app: tg-example
