apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-example
  template:
    metadata:
      labels:
        app: tg-example
    spec:
      containers:
      - image: okteto/tg-example:golang
        name: tg-example
---
apiVersion: v1
kind: Service
metadata:
  name: tg-example
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "tg-example"
    port: 8080
  selector:
    app: tg-example
