apiVersion: v1
kind: Secret
metadata:
  name: nasa-apod-bot
data:
  api-key: OU1HUHBwaEt4cksyUEF3OGxVdlVRSlFuRVFIOHppS01KakZFRFo5Qg==
  endpoint: aHR0cHM6Ly90Zy1leGFtcGxlLWZhcnd5ZGkuY2xvdWQub2t0ZXRvLm5ldC8=